/**
 * useDailyRoom — reusable Daily.co hook for IVEP.
 *
 * Wraps @daily-co/daily-js to provide a stable, React-idiomatic interface
 * for joining/leaving rooms, managing media tracks, and tracking participants.
 *
 * Usage:
 *   const daily = useDailyRoom({ roomUrl, token, startVideoOff, startAudioOff });
 *   daily.toggleMic();  daily.toggleCam();  daily.leave();
 */

'use client';

import { useEffect, useRef, useState, useCallback } from 'react';

// We import the global daily-js build (compatible with Next.js SSR)
// Types are intentionally broad so we don't need a @types package.

// ── Participant shape exposed by this hook ─────────────────────────────────

export interface DailyParticipant {
  sessionId: string;
  userId: string;
  userName: string;
  local: boolean;
  videoTrack: MediaStreamTrack | null;
  audioTrack: MediaStreamTrack | null;
  videoOn: boolean;
  audioOn: boolean;
  screenVideoTrack: MediaStreamTrack | null;
}

export interface DailyRoomMessage {
  id: string;
  senderId: string;
  senderName: string;
  text: string;
  createdAt: string;
  local: boolean;
}

// ── Hook options ───────────────────────────────────────────────────────────

export interface UseDailyRoomOptions {
  /** Full Daily room URL, e.g. https://myapp.daily.co/my-room */
  roomUrl: string;
  /** Meeting token generated by the backend */
  token: string;
  /** Start with camera disabled (used for audience viewers) */
  startVideoOff?: boolean;
  /** Start with mic disabled (used for audience viewers) */
  startAudioOff?: boolean;
  /** Fire when the local participant successfully joins */
  onJoined?: () => void;
  /** Fire when local participant leaves or is kicked */
  onLeft?: () => void;
  /** Fire on fatal errors */
  onError?: (msg: string) => void;
}

// ── Hook return type ───────────────────────────────────────────────────────

export interface UseDailyRoomResult {
  callObject: any;
  joined: boolean;
  error: string | null;
  reconnecting: boolean;
  localParticipant: DailyParticipant | null;
  remoteParticipants: DailyParticipant[];
  /** All participants including local */
  allParticipants: DailyParticipant[];
  roomMessages: DailyRoomMessage[];
  toggleMic: () => Promise<void>;
  toggleCam: () => Promise<void>;
  toggleScreenShare: () => Promise<void>;
  sendRoomMessage: (text: string) => Promise<void>;
  removeParticipant: (sessionId: string) => Promise<boolean>;
  leave: () => Promise<void>;
  reconnect: () => Promise<void>;
}

// ── Helper: convert a Daily participant object to our type ─────────────────

function toParticipant(p: any): DailyParticipant {
  const tracks = p.tracks || {};
  return {
    sessionId: p.session_id,
    userId: p.user_id || p.session_id,
    userName: p.user_name || 'Guest',
    local: !!p.local,
    videoTrack: tracks.video?.persistentTrack ?? null,
    audioTrack: tracks.audio?.persistentTrack ?? null,
    videoOn: tracks.video?.state === 'playable',
    audioOn: tracks.audio?.state === 'playable',
    screenVideoTrack: tracks.screenVideo?.persistentTrack ?? null,
  };
}

// ── Main hook ──────────────────────────────────────────────────────────────

export function useDailyRoom({
  roomUrl,
  token,
  startVideoOff = false,
  startAudioOff = false,
  onJoined,
  onLeft,
  onError,
}: UseDailyRoomOptions): UseDailyRoomResult {
  const callRef = useRef<any>(null);
  const localUserIdRef = useRef<string>('');
  const seenMsgIdsRef = useRef<Set<string>>(new Set());
  const [joined, setJoined] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [reconnecting, setReconnecting] = useState(false);
  const [participants, setParticipants] = useState<Record<string, DailyParticipant>>({});
  const [roomMessages, setRoomMessages] = useState<DailyRoomMessage[]>([]);

  const pushRoomMessage = useCallback((message: DailyRoomMessage) => {
    if (!message.text.trim()) return;
    if (seenMsgIdsRef.current.has(message.id)) return;
    seenMsgIdsRef.current.add(message.id);
    setRoomMessages((prev) => {
      const next = [...prev, message];
      if (next.length > 200) return next.slice(-200);
      return next;
    });
  }, []);

  // ── Refresh participant state from the call object ──────────────────────

  const refreshParticipants = useCallback(() => {
    const co = callRef.current;
    if (!co) return;
    const raw = co.participants() as Record<string, any>;
    const mapped: Record<string, DailyParticipant> = {};
    for (const [id, p] of Object.entries(raw)) {
      mapped[id] = toParticipant(p);
    }
    setParticipants(mapped);
  }, []);

  // ── Initial join effect ─────────────────────────────────────────────────

  useEffect(() => {
    if (!roomUrl || !token) return;

    let co: any = null;

    const init = async () => {
      try {
        // Dynamically import so Next.js SSR doesn't try to run Daily in Node
        const DailyIframe = (await import('@daily-co/daily-js')).default;
        co = DailyIframe.createCallObject();
        callRef.current = co;

        // ── Event listeners ───────────────────────────────────────────────

        co.on('joined-meeting', (evt: any) => {
          setJoined(true);
          setError(null);
          setReconnecting(false);
          localUserIdRef.current = String(evt?.participant?.user_id || '');
          refreshParticipants();
          onJoined?.();
        });

        co.on('left-meeting', () => {
          setJoined(false);
          setParticipants({});
          setRoomMessages([]);
          seenMsgIdsRef.current.clear();
          onLeft?.();
        });

        co.on('app-message', (evt: any) => {
          const payload = evt?.data;
          if (payload?.type !== 'conference-chat') return;

          const text = String(payload.text || '').trim();
          if (!text) return;

          const createdAt = String(payload.createdAt || new Date().toISOString());
          const senderId = String(payload.senderId || evt?.fromId || evt?.fromSessionId || '');
          const senderName = String(payload.senderName || evt?.fromUserName || 'Participant');
          const id = String(payload.id || `${senderId}:${createdAt}:${text.slice(0, 24)}`);
          const isLocal = senderId.length > 0 && senderId === localUserIdRef.current;

          pushRoomMessage({
            id,
            senderId,
            senderName,
            text,
            createdAt,
            local: isLocal,
          });
        });

        co.on('participant-joined', refreshParticipants);
        co.on('participant-updated', refreshParticipants);
        co.on('participant-left', refreshParticipants);
        co.on('track-started', refreshParticipants);
        co.on('track-stopped', refreshParticipants);

        co.on('network-connection', (evt: any) => {
          const state = evt?.event || evt?.status || evt?.state;
          if (state === 'interrupted' || state === 'reconnecting') {
            setReconnecting(true);
          }
          if (state === 'connected') {
            setReconnecting(false);
            setError(null);
            refreshParticipants();
          }
        });

        co.on('error', (evt: any) => {
          const msg = evt?.errorMsg || 'Daily.co connection error';
          // Keep transient network glitches recoverable instead of hard-failing the room.
          if (/network|connection|reconnect|timeout|ice/i.test(msg)) {
            setReconnecting(true);
            return;
          }
          setError(msg);
          onError?.(msg);
        });

        // ── Join the room ─────────────────────────────────────────────────

        await co.join({
          url: roomUrl,
          token: token,
          startVideoOff,
          startAudioOff,
        });
      } catch (err: any) {
        const msg = err?.message || 'Failed to join video room';
        setError(msg);
        onError?.(msg);
      }
    };

    init();

    return () => {
      // Cleanup: leave and destroy call object on unmount
      co?.leave().catch(() => {}).finally(() => {
        co?.destroy();
      });
    };
    // Only re-run when joining credentials change. Controls (mute/unmute) do
    // NOT need a new call object — they operate on the existing co instance.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [roomUrl, token]);

  // ── Controls ───────────────────────────────────────────────────────────

  const toggleMic = useCallback(async () => {
    const co = callRef.current;
    if (!co) return;
    const current = co.localAudio();
    await co.setLocalAudio(!current);
    refreshParticipants();
  }, [refreshParticipants]);

  const toggleCam = useCallback(async () => {
    const co = callRef.current;
    if (!co) return;
    const current = co.localVideo();
    await co.setLocalVideo(!current);
    refreshParticipants();
  }, [refreshParticipants]);

  const toggleScreenShare = useCallback(async () => {
    const co = callRef.current;
    if (!co) return;
    const localP = co.participants()?.local;
    const isSharing = localP?.screen;
    if (isSharing) {
      await co.stopScreenShare();
    } else {
      await co.startScreenShare();
    }
    refreshParticipants();
  }, [refreshParticipants]);

  const sendRoomMessage = useCallback(async (text: string) => {
    const co = callRef.current;
    const msgText = text.trim();
    if (!co || !msgText) return;

    const local = co.participants()?.local;
    const senderId = String(local?.user_id || local?.session_id || localUserIdRef.current || 'local');
    const senderName = String(local?.user_name || 'You');
    const createdAt = new Date().toISOString();
    const id = `${senderId}:${createdAt}:${Math.random().toString(36).slice(2, 10)}`;

    const payload = {
      type: 'conference-chat',
      id,
      senderId,
      senderName,
      text: msgText,
      createdAt,
    };

    pushRoomMessage({
      id,
      senderId,
      senderName,
      text: msgText,
      createdAt,
      local: true,
    });

    await co.sendAppMessage(payload, '*');
  }, [pushRoomMessage]);

  const removeParticipant = useCallback(async (sessionId: string) => {
    const co = callRef.current;
    if (!co || !sessionId) return false;

    if (typeof co.eject === 'function') {
      await co.eject(sessionId);
      refreshParticipants();
      return true;
    }

    if (typeof co.removeParticipant === 'function') {
      await co.removeParticipant(sessionId);
      refreshParticipants();
      return true;
    }

    return false;
  }, [refreshParticipants]);

  const leave = useCallback(async () => {
    const co = callRef.current;
    if (!co) return;
    await co.leave().catch(() => {});
  }, []);

  const reconnect = useCallback(async () => {
    setReconnecting(true);
    setError(null);
    const co = callRef.current;
    if (!co) return;
    try {
      await co.leave().catch(() => {});
      await co.join({ url: roomUrl, token, startVideoOff, startAudioOff });
    } catch (err: any) {
      setError(err?.message || 'Reconnection failed');
    } finally {
      setReconnecting(false);
    }
  }, [roomUrl, token, startVideoOff, startAudioOff]);

  // ── Derived state ──────────────────────────────────────────────────────

  const all = Object.values(participants);
  const localParticipant = all.find((p) => p.local) ?? null;
  const remoteParticipants = all.filter((p) => !p.local);

  return {
    callObject: callRef.current,
    joined,
    error,
    reconnecting,
    localParticipant,
    remoteParticipants,
    allParticipants: all,
    roomMessages,
    toggleMic,
    toggleCam,
    toggleScreenShare,
    sendRoomMessage,
    removeParticipant,
    leave,
    reconnect,
  };
}
