/**
 * useDailyRoom — reusable Daily.co hook for IVEP.
 *
 * Wraps @daily-co/daily-js to provide a stable, React-idiomatic interface
 * for joining/leaving rooms, managing media tracks, and tracking participants.
 *
 * Usage:
 *   const daily = useDailyRoom({ roomUrl, token, startVideoOff, startAudioOff });
 *   daily.toggleMic();  daily.toggleCam();  daily.leave();
 */

'use client';

import { useEffect, useRef, useState, useCallback } from 'react';

// We import the global daily-js build (compatible with Next.js SSR)
// Types are inlined so we don't need a @types package
type DailyCall = any;
type DailyEventObject = any;

// ── Participant shape exposed by this hook ─────────────────────────────────

export interface DailyParticipant {
  sessionId: string;
  userId: string;
  userName: string;
  local: boolean;
  videoTrack: MediaStreamTrack | null;
  audioTrack: MediaStreamTrack | null;
  videoOn: boolean;
  audioOn: boolean;
  screenVideoTrack: MediaStreamTrack | null;
}

// ── Hook options ───────────────────────────────────────────────────────────

export interface UseDailyRoomOptions {
  /** Full Daily room URL, e.g. https://myapp.daily.co/my-room */
  roomUrl: string;
  /** Meeting token generated by the backend */
  token: string;
  /** Start with camera disabled (used for audience viewers) */
  startVideoOff?: boolean;
  /** Start with mic disabled (used for audience viewers) */
  startAudioOff?: boolean;
  /** Fire when the local participant successfully joins */
  onJoined?: () => void;
  /** Fire when local participant leaves or is kicked */
  onLeft?: () => void;
  /** Fire on fatal errors */
  onError?: (msg: string) => void;
}

// ── Hook return type ───────────────────────────────────────────────────────

export interface UseDailyRoomResult {
  callObject: DailyCall | null;
  joined: boolean;
  error: string | null;
  reconnecting: boolean;
  localParticipant: DailyParticipant | null;
  remoteParticipants: DailyParticipant[];
  /** All participants including local */
  allParticipants: DailyParticipant[];
  toggleMic: () => Promise<void>;
  toggleCam: () => Promise<void>;
  toggleScreenShare: () => Promise<void>;
  leave: () => Promise<void>;
  reconnect: () => Promise<void>;
}

// ── Helper: convert a Daily participant object to our type ─────────────────

function toParticipant(p: any): DailyParticipant {
  const tracks = p.tracks || {};
  return {
    sessionId: p.session_id,
    userId: p.user_id || p.session_id,
    userName: p.user_name || 'Guest',
    local: !!p.local,
    videoTrack: tracks.video?.persistentTrack ?? null,
    audioTrack: tracks.audio?.persistentTrack ?? null,
    videoOn: tracks.video?.state === 'playable',
    audioOn: tracks.audio?.state === 'playable',
    screenVideoTrack: tracks.screenVideo?.persistentTrack ?? null,
  };
}

// ── Main hook ──────────────────────────────────────────────────────────────

export function useDailyRoom({
  roomUrl,
  token,
  startVideoOff = false,
  startAudioOff = false,
  onJoined,
  onLeft,
  onError,
}: UseDailyRoomOptions): UseDailyRoomResult {
  const callRef = useRef<DailyCall | null>(null);
  const [joined, setJoined] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [reconnecting, setReconnecting] = useState(false);
  const [participants, setParticipants] = useState<Record<string, DailyParticipant>>({});

  // ── Refresh participant state from the call object ──────────────────────

  const refreshParticipants = useCallback(() => {
    const co = callRef.current;
    if (!co) return;
    const raw = co.participants() as Record<string, any>;
    const mapped: Record<string, DailyParticipant> = {};
    for (const [id, p] of Object.entries(raw)) {
      mapped[id] = toParticipant(p);
    }
    setParticipants(mapped);
  }, []);

  // ── Initial join effect ─────────────────────────────────────────────────

  useEffect(() => {
    if (!roomUrl || !token) return;

    let co: DailyCall | null = null;

    const init = async () => {
      try {
        // Dynamically import so Next.js SSR doesn't try to run Daily in Node
        const DailyIframe = (await import('@daily-co/daily-js')).default;
        co = DailyIframe.createCallObject();
        callRef.current = co;

        // ── Event listeners ───────────────────────────────────────────────

        co.on('joined-meeting', (evt: DailyEventObject) => {
          setJoined(true);
          setError(null);
          setReconnecting(false);
          refreshParticipants();
          onJoined?.();
        });

        co.on('left-meeting', () => {
          setJoined(false);
          setParticipants({});
          onLeft?.();
        });

        co.on('participant-joined', refreshParticipants);
        co.on('participant-updated', refreshParticipants);
        co.on('participant-left', refreshParticipants);
        co.on('track-started', refreshParticipants);
        co.on('track-stopped', refreshParticipants);

        co.on('network-connection', (evt: DailyEventObject) => {
          if (evt.event === 'interrupted') setReconnecting(true);
          if (evt.event === 'connected') {
            setReconnecting(false);
            refreshParticipants();
          }
        });

        co.on('error', (evt: DailyEventObject) => {
          const msg = evt?.errorMsg || 'Daily.co connection error';
          setError(msg);
          onError?.(msg);
        });

        // ── Join the room ─────────────────────────────────────────────────

        await co.join({
          url: roomUrl,
          token: token,
          startVideoOff,
          startAudioOff,
        });
      } catch (err: any) {
        const msg = err?.message || 'Failed to join video room';
        setError(msg);
        onError?.(msg);
      }
    };

    init();

    return () => {
      // Cleanup: leave and destroy call object on unmount
      co?.leave().catch(() => {}).finally(() => {
        co?.destroy();
      });
    };
    // Only re-run when joining credentials change. Controls (mute/unmute) do
    // NOT need a new call object — they operate on the existing co instance.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [roomUrl, token]);

  // ── Controls ───────────────────────────────────────────────────────────

  const toggleMic = useCallback(async () => {
    const co = callRef.current;
    if (!co) return;
    const current = co.localAudio();
    await co.setLocalAudio(!current);
    refreshParticipants();
  }, [refreshParticipants]);

  const toggleCam = useCallback(async () => {
    const co = callRef.current;
    if (!co) return;
    const current = co.localVideo();
    await co.setLocalVideo(!current);
    refreshParticipants();
  }, [refreshParticipants]);

  const toggleScreenShare = useCallback(async () => {
    const co = callRef.current;
    if (!co) return;
    const localP = co.participants()?.local;
    const isSharing = localP?.screen;
    if (isSharing) {
      await co.stopScreenShare();
    } else {
      await co.startScreenShare();
    }
    refreshParticipants();
  }, [refreshParticipants]);

  const leave = useCallback(async () => {
    const co = callRef.current;
    if (!co) return;
    await co.leave().catch(() => {});
  }, []);

  const reconnect = useCallback(async () => {
    setReconnecting(true);
    setError(null);
    const co = callRef.current;
    if (!co) return;
    try {
      await co.leave().catch(() => {});
      await co.join({ url: roomUrl, token, startVideoOff, startAudioOff });
    } catch (err: any) {
      setError(err?.message || 'Reconnection failed');
    } finally {
      setReconnecting(false);
    }
  }, [roomUrl, token, startVideoOff, startAudioOff]);

  // ── Derived state ──────────────────────────────────────────────────────

  const all = Object.values(participants);
  const localParticipant = all.find((p) => p.local) ?? null;
  const remoteParticipants = all.filter((p) => !p.local);

  return {
    callObject: callRef.current,
    joined,
    error,
    reconnecting,
    localParticipant,
    remoteParticipants,
    allParticipants: all,
    toggleMic,
    toggleCam,
    toggleScreenShare,
    leave,
    reconnect,
  };
}
